### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by sadmankiba** [luca-vercelli/dictat-skill#2]
After `begin dictation` command, the following error is shown in the `Mycroft` log:

```
~~~~297031 | mycroft.skills.settings:_issue_api_call:306 | Failed to upload skill settings meta for @5a4e249e-ad61-4255-85b9-d02c32079685|dictat-skill
Traceback (most recent call last):
  File "/home/sakib/mycroft-core/mycroft/skills/settings.py", line 304, in _issue_api_call
    self.api.upload_skill_metadata(self.settings_meta)
  File "/home/sakib/mycroft-core/mycroft/api/__init__.py", line 371, in upload_skill_metadata
    return self.request({
  File "/home/sakib/mycroft-core/mycroft/api/__init__.py", line 64, in request
    return self.send(params)
  File "/home/sakib/mycroft-core/mycroft/api/__init__.py", line 147, in send
    return self.get_response(response, no_refresh)
  File "/home/sakib/mycroft-core/mycroft/api/__init__.py", line 170, in get_response
    raise HTTPError(data, response=response)
requests.exceptions.HTTPError: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
~~~~ncountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

After that, all speeches are ignored and no text is generated in current application. I needed to get out of dictation mode by typing `stop dictating` in mycroft shell.

**Comment by luca-vercelli** [comment]
Hello, are you sure this is an issue with dictat? other skills do work?
